# Generated by Django 3.2.16 on 2023-04-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_editpostmodel_editpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditPostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='EditPost',
        ),
    ]
